### ISSUE TITLE
Cant' pickle module error 

### ISSUE THREAD

**Issue by DavidAkinpelu** [ischoegl/ctwrap#3]
I got the error message "Cant' pickle module" when running the parallel version of adiabatic_flame example, Ignition_example and minimal_example without altering the default yaml files.

Operating system: Windows 10
Cantera Version: 2.40

![Error](https://user-images.githubusercontent.com/43585081/57882334-11216f80-77e9-11e9-8bca-b14714edb2b7.JPG)

**Comment by ischoegl** [comment]
Superseded by #7
