### ISSUE TITLE
Fix parallel runs on Windows

### ISSUE THREAD

**Issue by ischoegl** [ischoegl/ctwrap#7]
Currently the `Simulation` object is created from a fully instantiated module, which creates issues when running parallel on windows (Linux allows for pickling of objects, but Windows does not: currently, objects - i.e. simulation modules - are pickled when they are passed to workers in `multiprocessing`). 

I believe a straight-forward solution would be to just grab the name of the module in `Simulation.from_module`, and only store the path of the module. For the actual simulation, the module can be re-loaded in `Simulation.run`.

Supersedes #3

**Comment by ischoegl** [comment]
An even simpler solution would allow passing a `str` with the module name to `Simulation.from_module`, and use the string to load the module before passing it to the constructor.

**Comment by ischoegl** [comment]
... `importlib` ... see https://stackoverflow.com/questions/8718885/import-module-from-string-variable

**Comment by DavidAkinpelu** [comment]
Okay
